services:
  caddy:
    volumes:
      - ./Caddyfile.cloudflare:/etc/caddy/Caddyfile:ro

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      TUNNEL_TRANSPORT_PROTOCOL: http2
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - caddy
